chore(deps): misc dependencies updates
silviogutierrez/reactivated pull request #381
Opened 2024-11-05 22:06 UTC by crgwbr

Highlights: mypy, django-stubs, express v5, and eslint 9 (which is the biggest change).

2024-11-05 22:14 UTC, silviogutierrez commented
eslint9 is something I've been holding back on because it broke so much stuff.

I'll have to play around with it, but if this "just works" this is amazing. I dreaded that upgrade (and others did too).

Alternatively we can factor out the other dependency updates.

2024-11-29 01:36 UTC, silviogutierrez commented
@crgwbr : I think I fixed this with #384 

I also made the workflow process looser. I believe any changes should just auto run.

2024-11-29 05:31 UTC, silviogutierrez commented
Update here, mostly seems to work fine. I'm using the snapshot to test against my largest project codebase, and will need some time to see if there are any blockers.

So far so good.

2024-12-05 17:19 UTC, silviogutierrez requested changes
Almost ready to go, against my largest project.

Only issue I had on Mypy, maybe a regression or maybe you don't run into it.

Some models with `MyModel.objects.annotate` are now coming back as Any instead of annotated. I think it's those with custom managers. Have you run into this?

2024-12-05 17:19 UTC, silviogutierrez commented on development/eslint.config.js
We're opinionated, right? Why don't we put all of this in the main eslintrc file?

That makes the default eslint.config just a re-export and much cleaner. 

While we're at it, can we rename the shared config `eslint.config` instead of `eslintrc`

2024-12-05 17:19 UTC, silviogutierrez commented on development/eslint.config.js
And also the end-user eslint files should be `.ts` as per https://github.com/eslint/eslint/discussions/17726

That means we can have a 100% JS-free base project.

2024-12-13 19:49 UTC, crgwbr commented on development/eslint.config.js
Done

2024-12-13 21:12 UTC, silviogutierrez commented
@crgwbr : this was huge, thank you.

I made a minor update: just re-export reactivated's eslint for the happy path. You can, of course, manipulate it if you want.

2024-12-13 21:13 UTC, silviogutierrez approved these changes

2024-12-13 22:04 UTC, merged